two-final/Main/urls.py
from django.urls import path, include
from Main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.post_detail, name='post_detail'),
    path('career/', views.career, name='career'),
    path('career/<slug:slug>/', views.career_detail, name='career_detail'),
    path('about/', views.about, name='about'),
    path('service/', views.service, name='service'),


    path('automation-testing/', views.automation, name='automation'),
    path('functional-Testing/', views.functional, name='functional'),
    path('performance-Testing/', views.performance, name='performance'),
    path('application-Testing/', views.application, name='application'),
    path('cloud-testing/', views.cloud, name='cloud'),
    path('mobile-app-testing/', views.mobile, name='mobile'),
    path('data-analytics-testing/', views.data, name='data'),
    path('cx-testing/', views.cx, name='cx'),
    path('game-testing/', views.game, name='game'),
    path('integration-and-testing/', views.integration, name='integration'),
    path('iot-testing/', views.iot, name='iot'),
    path('devops/', views.devops, name='devops'),
    path('sales/', views.sales, name='sales'),
    path('rpa/', views.rpa, name='rpa'),
    path('accessibility/', views.accessibility, name='accessibility'),
]

two-final/TestSync/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Main.urls', 'Main'), namespace='Main')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    






  

two-final/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- COMMON TAGS -->
  <meta charset="utf-8">
  <title>BLOG | TestSync Global</title>
  <!-- Search Engine -->
  <meta name="description"
    content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
  <meta name="image" content="\assets\images\icon.png">
  <!-- Schema.org for Google -->
  <meta itemprop="name" content="BLOG | TestSync Global">
  <meta itemprop="description"
    content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
  <meta itemprop="image" content="\assets\images\icon.png">
  <!-- Twitter -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="BLOG | TestSync Global">
  <meta name="twitter:description"
    content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
  <meta name="twitter:image:src" content="https://www.linkpicture.com/q/metaimg.png">
  <!-- Open Graph general (Facebook, Pinterest & Google+) -->
  <meta name="og:title" content="BLOG | TestSync Global">
  <meta name="og:description"
    content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
  <meta name="og:image" content="https://www.linkpicture.com/q/metaimg.png">
  <meta name="og:url" content="https://draft4client.web.app/TestSync Global">
  <meta name="og:site_name" content="BLOG | TestSync Global">
  <meta name="og:type" content="website">

  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="css/aos.css"> -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nav-footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/service.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/05113fe05e.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
    <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="anonymous" />
  </head>
  
  <body>
  
  
  
    <!-- loader -->
    <div id="loading">
      <div class="container">
        <div class="loader"></div>
        <div class="loader"></div>
        <div class="loader"></div>
      </div>
  
    </div>
    <!-- loader -->
  {% include "nav.html" %}

  <div data-aos="fade-down" class="container service-hero">
    <div class="row gx-5 ser-vice ">

      <div class="col-md-8">
        <h2 class="">Read Our <span class="text-underline" >Blogs</span> </h2>

      </div>

      <div class="col-md-3">
        
      </div>

    </div>
  </div>

  <!-- blog section start -->


  <div class="py-5 service-7">
    <div class="container">
      <!-- Row  -->
      <div class="row gx-2">
        {% for post in posts %}
        <!-- Column -->
        <a href="{% url 'Main:post_detail' post.slug %}" class="linking">
        <div class="col-md-4">
          <div class="blog-box">
            <img class="rounded img-fluid blog-img" src="/media/{{ post.photo }}" alt="wrappixel kit" />
            <div class="mt-4">
              <h6 class="font-weight-medium">{{ post.title }}</h6>
              <!-- <p class="mt-3">{{ post.body|slice:":100"|safe }}...</p> -->
              <a href="{% url 'Main:post_detail' post.slug %}" class="linking">Read More</a>
            </div>
          </div>
        </div>
      </a>
        {% endfor %}
      </div>
    </div>
  </div>

  <!-- blog section end -->






  {% include "footer.html" %}
</body>



</html>

two-final/templates/career.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<!-- COMMON TAGS -->
<meta charset="utf-8">
<title>CAREER | TestSync Global</title>
<!-- Search Engine -->
<meta name="description" content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
<meta name="image" content="assets\images\icon.png">
<!-- Schema.org for Google -->
<meta itemprop="name" content="CAREER | TestSync Global">
<meta itemprop="description" content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
<meta itemprop="image" content="assets\images\icon.png">
<!-- Twitter -->
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="CAREER | TestSync Global">
<meta name="twitter:description" content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
<meta name="twitter:image:src" content="https://www.linkpicture.com/q/metaimg.png">
<!-- Open Graph general (Facebook, Pinterest & Google+) -->
<meta name="og:title" content="CAREER | TestSync Global">
<meta name="og:description" content="TestSync Global we offer comprehensive solutions to meet all of your software testing and quality assurance needs in a single destination">
<meta name="og:image" content="https://www.linkpicture.com/q/metaimg.png">
<meta name="og:url" content="https://draft4client.web.app/TestSync Global">
<meta name="og:site_name" content="CAREER | TestSync Global">
<meta name="og:type" content="website">

  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- <link rel="stylesheet" href="{% static 'css/aos.css' %}"> -->
  <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icon.png' %}">
  <link rel="stylesheet" href="{% static 'css/career.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/contact-us.css' %}">
  <link rel="stylesheet" href="{% static 'css/nav-footer.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/service.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="https://kit.fontawesome.com/05113fe05e.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
  <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="crossorigin="anonymous" />
</head>

<body>



  <!-- loader -->
  <div id="loading">
    <div class="container">
      <div class="loader"></div>
      <div class="loader"></div>
      <div class="loader"></div>
    </div>

  </div>
  <!-- loader -->

  {% include "nav.html" %}




  <div data-aos="fade-down" class="container service-hero">
    <div class="row gx-5 ser-vice ">

      <div class="col-md-8">
        <h1> <span class="normal-heading">JOIN THE </span> <br> <span class="bold-heading"><span class="text-underline" >TEAM</span></span> </h1>

        <div class="mt-4 black-para">
        <p>
            At TestSync Global, we are always looking for passionate and talented individuals to join our team. We offer a dynamic work environment and opportunities for growth and development. If you are interested in joining our team, please send your resume and cover letter to our HR department. We look forward to hearing from you.
        </p>
      </div>

      </div>

      <div class="col-md-3">
        
      </div>

    </div>
  </div>


  <hr>

  <!-- why work -->


  <div class="container pt-4">

    <h2 class="text-center" > <span class="normal-heading">About <span class="bold-heading"><span class="text-underline" >Working</span></span> At TestSync Global </span> <br>  </h2>


  <div class="row col-14 gx-5 justify-content-between why-work">


    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/consulting.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Conductive Environment</h6>
            <p>Open communication, and collaboration </p>
          </div>
    </div>

    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/apple-juice.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Healthy Meals And Snacks</h6>
            <p>Promoting overall health and wellbeing </p>
          </div>
    </div>

    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/gadgets.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Best Gadgets</h6>
            <p>Cutting-edge tech with user-friendly design </p>
          </div>
    </div>

    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/success.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Shared Success</h6>
            <p>Collective achievement that benefits everyone </p>
        </div>
  </div>

    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/learning.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Culture of learning</h6>
            <p>Continuous growth and development </p>
          </div>
    </div>

    <div class="col-lg-6 col-md-6 col-12 my-4 why-work-box ">
        <div class="why-img">
            <img class="mb-4" src="{% static 'assets/images/team.png' %}" alt="">
          </div>
          <div class="why-desc">
            <h6>Great Team</h6>
            <p>Leveraging the strengths of each individual </p>
          </div>
    </div>



  </div>

</div>

<!-- why work end -->

    <hr class="mb-5">

    <!-- service section tab start -->

<div class="container ">
    <div class="col">
      <h2 class="ml-3" > <span class="normal-heading">Open <span class="bold-heading"><span class="text-underline" >Jobs</span></span> </span> </h2>

    </div>
  </div>



  <div class="container my-4">
    <div class="row">
      {% for career in careers %}
      <div class="col-md-6 col-12">
        <div class="card border-2 m-3 rounded-xs">
          <div class="card-body">
            
            <h4>{{career.title}}</h4>
            <hr>
            <h6>Experience - {{career.experience}} years</h5>
            <h6>Location - {{career.location}}</h5>
            <hr>
            <a class="job-btn" href="{% url 'Main:career_detail' career.slug %}">APPLY NOW</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>




  {% include "footer.html" %}
</body>



</html>

two-final/templates/contact_mail.html
<!DOCTYPE html>
<html>
<head>
<style>

h1{
    font-family: Arial, Helvetica, sans-serif;
}

#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 600px;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #1c1c1c;
  color: white;
}
</style>
</head>
<body>

<h1>You've got a New Contact</h1>

<table id="customers">

  <tr>
    <td> Name:</td>
    <td>{{name}}</td>
  </tr>
    <tr>
        <td>Email:</td>
        <td>{{email}}</td>
    </tr>
    <tr>
        <td>Phone no:</td>
        <td>{{phone_no}}</td>
    </tr>
    <tr>
      <td> Applied:</td>
      <td>{{message}}</td>
    </tr>
    <tr>
      <td>Time:</td>
      <td>{{date_added}}</td>
    </tr>

</table>

</body>
</html>

two-final/templates/footer.html
  <!-- footer Start -->
  {% load static %}

  <footer class="footer-14398">

    <div class="container">
      <div class="row mb-5">
        <div class="col-md-3 footer-address">
          <a href="/" class="footer-site-logo">TestSync Global</a>
          <p style="width: 80%" >As a global software testing and quality assurance company, we offer comprehensive solutions to meet all of
            your software testing and quality assurance needs in a single destination. </p>

            <a href="Mailto:sales@TestSync Global.com"> <i class="fa-solid fa-envelope"></i> Sales@TestSync Global.com</a>
            
        </div>

        <div class="col-md-2 ml-auto">
          <h3>COMPANY</h3>
          <ul class="list-unstyled links">
            <li><a href="{% url 'Main:index' %}">HOME</a></li>
            <!-- <li><a href="{% url 'Main:blog' %}">Blog</a></li> -->
            <li><a href="{% url 'Main:career' %}">CAREER</a></li>
            <li><a href="{% url 'Main:about' %}">ABOUT US</a></li>
            <li><a href="{% url 'Main:contact' %}">CONTACT US</a></li>
          </ul>
        </div>



        <div class="col-md-3 ml-auto">
          <h3>SERVICES</h3>
          <ul class="list-unstyled links">
            <li><a href="{% url 'Main:functional' %}" >FUNCTIONAL TESTING</a></li>
            <li><a href="{% url 'Main:performance' %}" >PERFORMANCE ENGINEERING & TESTING</a></li>
            <li><a href="{% url 'Main:application' %}" >APPLICATION SECURITY TESTING</a></li>
            <li><a href="{% url 'Main:mobile' %}" >MOBILE APP TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:data' %}" >DATA ANALYTICS TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:automation' %}" >AUTOMATION TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:game' %}" >GAME TESTING​ SERVICES</a></li>
            <li><a href="{% url 'Main:integration' %}" >INTEGRATION AND TESTING (I&T)</a></li>
            <li><a href="{% url 'Main:iot' %}" >IoT TESTING</a></li>
            <li><a href="{% url 'Main:cloud' %}" >CLOUD TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:cx' %}" >CX TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:devops' %}" >DEVOPS TESTING SERVICES</a></li>
            <li><a href="{% url 'Main:sales' %}" >SALES-FORCE TESTING</a></li>
            <li><a href="{% url 'Main:rpa' %}" >RPA SERVICES</a></li>
            <li><a href="{% url 'Main:accessibility' %}" >ACCESSIBILITY TESTING</a></li>
          </ul>
        </div>


        <div class="col-md-3 ml-auto footer-address">
          <h3>VISIT US</h3>

          <p> <b>India Office:</b> </p>
          <p>Office no. 316, Crossroads, Bhumkar Chowk, Wakad, Pune.</p>
            <i class="fa-solid fa-phone"></i> <a href="tel:+919876543210"> +91 9876543210</a>

            <hr style="background-color: white" >

          <p> <b>Germany Office:</b> </p>
          <p>Grumbrechtstraße 70,21075</p>
          <i class="fa-solid fa-phone"></i> <a href="tel:+911234567890"> +911234567890</a>

          
        </div>
        


        
      </div>
      <hr class="hr" />
      <div class="row mb-0">

        <div class="col-md-6 text-md-left">
          <ul style="margin-bottom: 0;" class="list-unstyled link-menu nav-left">
            <!-- <li><a href="#">Privacy Policy</a></li> -->
            <!-- <li><a href="#">Terms &amp; Conditions</a></li> -->
            <p></p>
          </ul>
        </div>
        <div class="col-md-6 text-md-right">
          <ul style="margin-bottom: 0;" class="list-unstyled social nav-right">
            <li><a target="_blank" href="https://www.linkedin.com"><span class="icon-twitter"><i class="fa-brands fa-linkedin-in"></i></span></a></li>
            <li><a target="_blank" href="https://www.instagram.com"><span class="icon-instagram"><i class="fa-brands fa-instagram"></i></span></a></li>
            <li><a target="_blank" href="https://www.facebook.com"><span class="icon-facebook"><i class="fa-brands fa-facebook-f"></i></span></a></li>
        </ul>
        </div>
      </div>
      <hr class="hr" />

      <div class="row">
        <div class="col-md-7">
          <p>© Copyright TestSync Global - All Rights Reserved</p>
        </div>
      </div>
    </div>

    </div>
  </footer>
  <!-- footer end -->


  <script type="text/javascript">
    $(document).ready(function () {
      $('.customer-tools').slick({

        slidesToShow: 7,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 1000,
        arrows: false,
        dots: false,
        pauseOnHover: false,
        responsive: [{
          breakpoint: 768,
          settings: {
            slidesToShow: 4
          }
        }, {
          breakpoint: 520,
          settings: {
            slidesToShow: 3
          }
        }]
      });
    });

    $('#pause').hover(function () {
      $('.slider').hover('slickPause');
    });

    $(document).ready(function () {
      $('.customer-logos').slick({
        slidesToShow: 6,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 1000,
        arrows: false,
        dots: false,
        pauseOnHover: false,
        responsive: [{
          breakpoint: 768,
          settings: {
            slidesToShow: 4
          }
        }, {
          breakpoint: 520,
          settings: {
            slidesToShow: 3
          }
        }]
      });
    });



    $(window).load(function () {
      $('#loading').hide();
    });


  </script>



  <script>
    function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
    }

    // Get the element with id="defaultOpen" and click on it
    document.getElementById("defaultOpen").click();
  </script>
  <script src="{% static 'js/aos.js' %}"></script>

  <!--Start of Tawk.to Script-->
<script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/640469cc4247f20fefe4105d/1gqojqid4';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/slick.js' %}"></script>

two-final/templates/home.html
<h1>asdadf</h1>
{% load static %}
<img src="{% static 'alzi-20200610-ha.jpg' %}" alt="My image">

{% for q in q %}
<img src="media/{{ q.photo }}" alt="">
<li>{{ q.name }}</li> 

{% endfor %}

"{% static '
' %}"

two-final/templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


  <meta charset="utf-8">  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Search Engine -->
  <title>{{ post.title }}</title>
  <meta name="description" content="{{ post.meta_description }}">
  <meta name="image" content="/media/{{ post.photo }}">
  <meta name="keywords" content="{{ post.meta_keywords }}">
  <!-- Schema.org for Google -->
  <meta itemprop="name" content="{{ post.title }}">
  <meta itemprop="name" content="{{ post.meta_description }}">
  <meta itemprop="description" content="{{ post.meta_description }}">
  <meta itemprop="image" content="/media/{{ post.photo }}">
  <!-- Twitter -->
  <meta name="twitter:card" content="{{ post.photo }}">
  <meta name="twitter:title" content="{{ post.meta_title }}">
  <meta name="twitter:description" content="{{ post.meta_description }}">
  <meta name="twitter:image:src" content="/media/{{ post.photo }}">
  <!-- Open Graph general (Facebook, Pinterest & Google+) -->
  <meta name="og:title" content="{{ post.meta_title }}">
  <meta name="og:description"content="{{ post.meta_description }}">
  <meta name="og:image" content="/media/{{ post.photo }}">
   <!-- <link rel="stylesheet" href="css/aos.css"> -->
   <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icon.png' %}">
   <link rel="stylesheet" href="{% static 'css/about.css' %}">
   <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
   <link rel="stylesheet" href="{% static 'css/nav-footer.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="{% static 'css/service.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <script src="https://kit.fontawesome.com/05113fe05e.js" crossorigin="anonymous"></script>
   <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
   <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
     integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
     crossorigin="anonymous" />

</head>
<body>



{% include "nav.html" %}


<div class="container my-5 p-4">

  <div class="post">
  <div class="post-img mb-3">
  <img src="/media/{{ post.photo }}" alt="">
  </div>

    <h1 class="title mb-3">{{ post.title }}</h1>

    <p class="post-date">

    Posted at {{ post.date_added }}
    </p>


    <p>{{ post.body|safe}}</p>

    <hr>

  </div>

</div>

{% include "footer.html" %}

  
</body>
</html>

two-final/templates/sucessfull.html
{% load static %}
   <!-- <link rel="stylesheet" href="css/aos.css"> -->
   <title>Sucess</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">


   <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icon.png' %}">
   <link rel="stylesheet" href="{% static 'css/about.css' %}">
   <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
   <link rel="stylesheet" href="{% static 'css/nav-footer.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="{% static 'css/service.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <script src="https://kit.fontawesome.com/05113fe05e.js" crossorigin="anonymous"></script>
   <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
   <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
     integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
     crossorigin="anonymous" />
 </head>
{% include "nav.html" %}

<style>
    .thankyou{
      display: flex;
      flex-direction: column;
      justify-content: center;
      text-align: center;
      height: 100vh;
      max-width: 600px;
      margin: auto;
      padding: 20px;
    }

    .thankyou h1{
      font-size: 65px !important;
    }

    .thankyou p{
      font-size: 20px;
    }


    @media only screen and (min-width: 700px) {
      .thankyou h1{
          font-size: 50px !important;
      }
    }

    .read-more{
        color: black;
        padding: 10px;
        border: solid 2px;
    }
  </style>

  <div class="thankyou">
    <h1>
      Thank You
    </h1>
    <p>Your request has been acknowledged and one of our team members will be in contact with you shortly. You can also contact us on <a href="tel:89291 30516">89291 30516</a> if you would like to speak to us right away.</p>
      <a class="read-more" href="{% url 'Main:index' %}">Return To Home</a>
  </div>



{% include "footer.html" %}